/*


~~~~~~~~~~Data file~~~~~~~~~~

  This is the data file which contains all the questions and answers.
It is linked to the file 'main.c' which contains the Start Menu, Topic
Selection Menu and Credits page.

  All the questions and answers are inside switch statements and are
printed by printf() statements. Each function defines a topic. More
topics can be add by introducing an extra function and listing & linking
it in the 'main.c' file


*/

int a[10]; //Global variable - used to store random nos generated by rando()

void rando() //used to generate a random series of nos
{
  int i,j,b,n=0;
  time_t t; //for the srand()
  srand((unsigned) time(&t)); //this line ensures a completely random number generation
  for(i=0;i<10;i++)
  {
    b=rand() % 11; // the %11 put the limit from 1 to 10
    for(j=0;j<=n;j++)
    {
      if(a[j]==b||b==0)
      {
        b=rand() % 11;
        j=-1;
      }
    }
    a[i]=b; //the generated no is stored in the global variable
    n++;
  }
}

void start(); //declared in order to link it to the 'main.c' file

void restart() //restarts from the start()
{
    char ent;
    printf("\n\n\t\t\t\t  ~~~~~Press Enter to RESTART~~~~~");
    scanf("%c",&ent);
    start();
}

void topic0() //Topic name is General Knowledge, UI done
{
    char inp;
    int count=0,r=0,i,c,ia,corr=0,wrong=0;
    rando();
    for(i=0;i<10;i++)
    {
      system("clear");
      count++;
      test:
      printf("\n\n\t\t\t\t      ~~~~~Question %d~~~~~\n",count);
      printf("\n\t\t\t    Correct Answers=%d        Wrong Answers=%d\n\n\n\n",corr,wrong);
      r=a[i];
      switch(r)
      {
        case 1:{
                c=1;
                //c is the correct option number
                printf("\t\tGrand Central Terminal, Park Avenue, New York is the world's ________\n\n\n");
                printf("\t\t\t\t     1) largest railway station\n");
                printf("\t\t\t\t     2) highest railway station\n");
                printf("\t\t\t\t     3) longest railway station\n");
                printf("\t\t\t\t     4) None of the above\n");
                printf("\n\t\t\t\t   Enter correct option : ");
                scanf("%d",&ia);
                break;
               }
        case 2:{
                c=2;
                printf("\t\t   Entomology is the science that studies ________\n\n\n");
                printf("\t\t\t\t     1) Behavior of human beings\n");
                printf("\t\t\t\t     2) Insects\n");
                printf("\t\t\t\t     3) Decomposition\n");
                printf("\t\t\t\t     4) The formation of rocks\n");
                printf("\n\t\t\t\t   Enter correct option: ");
                scanf("%d",&ia);
                break;
               }
        case 3:{
                c=2;
                printf("\t Eritrea, which became the 182nd member of the UN in 1993, is in the continent of ________\n\n\n");
                printf("\t\t\t\t     1) Asia\n");
                printf("\t\t\t\t     2) Africa\n");
                printf("\t\t\t\t     3) Europe\n");
                printf("\t\t\t\t     4) Australia\n");
                printf("\n\t\t\t\t   Enter correct option : ");
                scanf("%d",&ia);
                break;
               }
        case 4:{
                c=2;
                printf("\t\t\t     Garampani sanctuary is located at ________\n\n\n");
                printf("\t\t\t\t     1) Junagarh, Gujarat\n");
                printf("\t\t\t\t     2) Diphu, Assam\n");
                printf("\t\t\t\t     3) Kohima, Nagaland\n");
                printf("\t\t\t\t     4) Gangtok, Sikkim\n");
                printf("\n\t\t\t\t   Enter correct option : ");
                scanf("%d",&ia);
                break;
               }
        case 5:{
                c=4;
                printf("\t\t    For which of the following disciplines is Nobel Prize awarded?\n\n\n");
                printf("\t\t\t\t     1) Physics and Chemistry\n");
                printf("\t\t\t\t     2) Physiology or Medicine\n");
                printf("\t\t\t\t     3) Literature, Peace and Economics\n");
                printf("\t\t\t\t     4) All of the above\n");
                printf("\n\t\t\t\t   Enter correct option : ");
                scanf("%d",&ia);
                break;
               }
        case 6:{
                c=2;
                printf("\t\t    Hitler party which came into power in 1933 is known as ________\n\n\n");
                printf("\t\t\t\t     1) Labour Party\n");
                printf("\t\t\t\t     2) Nazi Party\n");
                printf("\t\t\t\t     3) Ku-Klux-Klan\n");
                printf("\t\t\t\t     4) Democratic Party\n");
                printf("\n\t\t\t\t   Enter correct option : ");
                scanf("%d",&ia);
                break;
               }
        case 7:{
                c=2;
                printf("\t\t\t\t    FFC stands for ________\n\n\n");
                printf("\t\t\t\t     1) Foreign Finance Corporation\n");
                printf("\t\t\t\t     2) Film Finance Corporation\n");
                printf("\t\t\t\t     3) Federation of Football Council\n");
                printf("\t\t\t\t     4) None of the above\n");
                printf("\n\t\t\t\t   Enter correct option: ");
                scanf("%d",&ia);
                break;
               }
        case 8:{
                c=1;
                printf("\t\t\t      Fastest shorthand writer was ________\n\n\n");
                printf("\t\t\t\t     1) Dr. G. D. Bist\n");
                printf("\t\t\t\t     2) J.R.D. Tata\n");
                printf("\t\t\t\t     3) J.M. Tagore\n");
                printf("\t\t\t\t     4) Khudada Khan\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("%d",&ia);
                break;
               }
        case 9:{
                c=1;
                printf("\t    First human heart transplant operation conducted by Dr. Christiaan Barnard on\n\t\t\t     Louis Washkansky, was conducted in ________\n\n\n");
                printf("\t\t\t\t     1) 1967\n");
                printf("\t\t\t\t     2) 1968\n");
                printf("\t\t\t\t     3) 1958\n");
                printf("\t\t\t\t     4) 1922\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("%d",&ia);
                break;
               }
        case 10:{
                c=3;
                printf("\t\t\t      First Afghan War took place in ________\n\n\n");
                printf("\t\t\t\t     1) 1839\n");
                printf("\t\t\t\t     2) 1843\n");
                printf("\t\t\t\t     3) 1833\n");
                printf("\t\t\t\t     4) 1848\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("%d",&ia);
                break;
               }
        default:printf("Invalid Input\n\n\n");
      }
      if(ia==c)
      {
        corr++;
        printf("\n\t\t\t\t\t CORRECT ANSWER :)");
        getchar();
        scanf("%c",&inp);
      }
      else if(ia==1||ia==2||ia==3||ia==4)
      {
        wrong++;
        printf("\n\t\t\t\t\t  WRONG ANSWER :(");
        getchar();
        scanf("%c",&inp);
      }
      else
      {
        printf("\n\t\t\t\t  Invalid Option, please try again");
        getchar();
        scanf("%c",&inp);
        system("clear");
        goto test;
      }
    }
    system("clear");
    printf("\n\n\t\t\t        ~~~~~Topic: General Knowledge~~~~~");
    printf("\n\n\n\t\t\t\t\tCorrect Answers:%d\n\t\t\t\t\t Wrong Answers:%d\n",corr,wrong);
    restart();
}

void topic1() //Topic name is Science UI done
{
    char inp;
    int count=0,r=0,i,c,ia,corr=0,wrong=0;
    rando();
    for(i=0;i<10;i++)
    {
      system("clear");
      count++;
      test:
      printf("\n\n\t\t\t\t      ~~~~~Question %d~~~~~\n",count);
      printf("\n\t\t\t    Correct Answers=%d        Wrong Answers=%d\n\n\n\n",corr,wrong);
      r=a[i];
      switch(r)
      {
        case 1:{
                c=2;
                //c is the correct option number for that case
                printf("\t\tWhich of the following is a non metal that remains liquid at room temperature?\n\n\n");
                printf("\t\t\t\t     1) Phosphorous\n");
                printf("\t\t\t\t     2) Bromine\n");
                printf("\t\t\t\t     3) Chlorine\n");
                printf("\t\t\t\t     4) Helium\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("           %d",&ia);
                break;
               }
        case 2:{
                c=1;
                printf("\t\t\tNuclear sizes are expressed in a unit named ________\n\n\n");
                printf("\t\t\t\t     1) Fermi\n");
                printf("\t\t\t\t     2) Angstrom\n");
                printf("\t\t\t\t     3) Newton\n");
                printf("\t\t\t\t     4) Tesla\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 3:{
                c=2;
                printf("\t\t   Movement of cell against concentration gradient is called ________\n\n\n");
                printf("\t\t\t\t     1) osmosis\n");
                printf("\t\t\t\t     2) active transport\n");
                printf("\t\t\t\t     3) diffusion\n");
                printf("\t\t\t\t     4) passive transport\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 4:{
                c=1;
                printf("\t\t\t    Which of the following is used in pencils?\n\n\n");
                printf("\t\t\t\t     1) Graphite\n");
                printf("\t\t\t\t     2) Silicon\n");
                printf("\t\t\t\t     3) Charcoal\n");
                printf("\t\t\t\t     4) Phosphorous\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 5:{
                c=2;
                printf("\t\t      The absorption of ink by blotting paper involves ________\n\n\n");
                printf("\t\t\t\t     1) viscosity of ink\n");
                printf("\t\t\t\t     2) capillary action phenomenon\n");
                printf("\t\t\t\t     3) diffusion of ink through the blotting\n");
                printf("\t\t\t\t     4) siphon action\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 6:{
                c=1;
                printf("\t\t     The gas usually filled in the electric bulb is ________\n\n\n");
                printf("\t\t\t\t     1) nitrogen\n");
                printf("\t\t\t\t     2) hydrogen\n");
                printf("\t\t\t\t     3) carbon dioxide\n");
                printf("\t\t\t\t     4) oxygen\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 7:{
                c=1;
                printf("\t\t\t    Washing soda is the common name for ________\n\n\n");
                printf("\t\t\t\t     1) Sodium carbonate\n");
                printf("\t\t\t\t     2) Calcium bicarbonate\n");
                printf("\t\t\t\t     3) Sodium bicarbonate\n");
                printf("\t\t\t\t     4) Calcium carbonate\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 8:{
                c=1;
                printf("\t\t\t     Pollination is best defined as ________\n\n\n");
                printf("\t\t\t\t     1) transfer of pollen from anther to stigma\n");
                printf("\t\t\t\t     2) germination of pollen grains\n");
                printf("\t\t\t\t     3) growth of pollen tube in ovule\n");
                printf("\t\t\t\t     4) visiting flowers by insects\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 9:{
                c=2;
                printf("\t     Other than spreading malaria, anopheles mosquitoes are also vectors of ________\n\n\n");
                printf("\t\t\t\t     1) dengue fever\n");
                printf("\t\t\t\t     2) filariasis\n");
                printf("\t\t\t\t     3) encephalitis\n");
                printf("\t\t\t\t     4) yellow fever\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 10:{
                c=2;
                printf("\t\t\t   Photosynthesis takes place faster in ________\n\n\n");
                printf("\t\t\t\t     1) yellow light\n");
                printf("\t\t\t\t     2) white light\n");
                printf("\t\t\t\t     3) red light\n");
                printf("\t\t\t\t     4) darkness\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        default:printf("          Invalid Input\n\n\n");
      }
      if(ia==c)
      {
        corr++;
        printf("\n\t\t\t\t\t CORRECT ANSWER :)");
        getchar();
        scanf("%c",&inp);
      }
      else if(ia==1||ia==2||ia==3||ia==4)
      {
        wrong++;
        printf("\n\t\t\t\t\t  WRONG ANSWER :(");
        getchar();
        scanf("%c",&inp);
      }
      else
      {
        printf("\n\t\t\t\t  Invalid Option, please try again");
        getchar();
        scanf("%c",&inp);
        system("clear");
        goto test;
      }
    }
    system("clear");
    printf("\n\n\t\t\t\t     ~~~~~Topic: Science~~~~~");
    printf("\n\n\n\t\t\t\t\tCorrect Answers:%d\n\t\t\t\t\t Wrong Answers:%d\n",corr,wrong);
    restart();
}

void topic2() //Topic name is Technoogy UI done
{
    char inp;
    int count=0,r=0,i,c,ia,corr=0,wrong=0;
    rando();
    for(i=0;i<10;i++)
    {
      system("clear");
      count++;
      test:
      printf("\n\n\t\t\t\t      ~~~~~Question %d~~~~~\n",count);
      printf("\n\t\t\t    Correct Answers=%d        Wrong Answers=%d\n\n\n\n",corr,wrong);
      r=a[i];
      switch(r)
      {
        case 1:{
                c=2;
                //c is the correct option number
                printf("\t\tWhat is part of a database that holds only one type of information?\n\n\n");
                printf("\t\t\t\t     1) Report\n");
                printf("\t\t\t\t     2) Field\n");
                printf("\t\t\t\t     3) Record\n");
                printf("\t\t\t\t     4) File\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("           %d",&ia);
                break;
               }
        case 2:{
                c=4;
                printf("\t\tIn which decade with the first transatlantic radio broadcast occur?\n\n\n");
                printf("\t\t\t\t     1) 1850s\n");
                printf("\t\t\t\t     2) 1860s\n");
                printf("\t\t\t\t     3) 1870s\n");
                printf("\t\t\t\t     4) 1900s\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 3:{
                c=2;
                printf("\t\t       '.MOV' extension refers usually to what kind of file?\n\n\n");
                printf("\t\t\t\t     1) Image file\n");
                printf("\t\t\t\t     2) Animation/movie file\n");
                printf("\t\t\t\t     3) Audio file\n");
                printf("\t\t\t\t     4) MS Office document\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 4:{
                c=2;
                printf("\t\t\t\t     Who developed Yahoo?\n\n\n");
                printf("\t\t\t\t     1) Dennis Ritchie & Ken Thompson\n");
                printf("\t\t\t\t     2) David Filo & Jerry Yang\n");
                printf("\t\t\t\t     3) Vint Cerf & Robert Kahn\n");
                printf("\t\t\t\t     4) Steve Case & Jeff Bezos\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 5:{
                c=2;
                printf("\t\t    Which of the following is an example of non volatile memory?\n\n\n");
                printf("\t\t\t\t     1) VLSI\n");
                printf("\t\t\t\t     2) ROM\n");
                printf("\t\t\t\t     3) RAM\n");
                printf("\t\t\t\t     4) LSI\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 6:{
                c=4;
                printf("\t\t\t\t   What does VVVF stand for?\n\n\n");
                printf("\t\t\t\t     1) Variant Voltage Vile Frequency\n");
                printf("\t\t\t\t     2) Variable Velocity Variable Fun\n");
                printf("\t\t\t\t     3) Very Very Vicious Frequency\n");
                printf("\t\t\t\t     4) Variable Voltage Variable Frequency\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 7:{
                c=1;
                printf("\t\t     Who built the world's first binary digit computer: Z1...?\n\n\n");
                printf("\t\t\t\t     1) Konrad Zuse\n");
                printf("\t\t\t\t     2) Ken Thompson\n");
                printf("\t\t\t\t     3) Alan Turing\n");
                printf("\t\t\t\t     4) George Boole\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 8:{
                c=3;
                printf("\t\tIn a color television set using a picture tube a high voltage is \n          used to accelerate electron beams to light the screen. That voltage is about ________\n\n\n");
                printf("\t\t\t\t     1) 500 volts\n");
                printf("\t\t\t\t     2) 5 thousand volts\n");
                printf("\t\t\t\t     3) 25 thousand volts\n");
                printf("\t\t\t\t     4) 100 thousand volts\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 9:{
                c=2;
                printf("\t  Which consists of two plates separated by a dielectric and can store a charge?\n\n\n");
                printf("\t\t\t\t     1) Inductor\n");
                printf("\t\t\t\t     2) Capacitor\n");
                printf("\t\t\t\t     3) Relay\n");
                printf("\t\t\t\t     4) Transistor\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 10:{
                c=1;
                printf("\t\tCompact discs, (according to the original CD specifications) hold \n\t\t\t\t   how many minutes of music?\n\n\n");
                printf("\t\t\t\t     1) 74 mins\n");
                printf("\t\t\t\t     2) 56 mins\n");
                printf("\t\t\t\t     3) 60 mins\n");
                printf("\t\t\t\t     4) 90 mins\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        default:printf("          Invalid Input\n\n\n");
      }
      if(ia==c)
      {
        corr++;
        printf("\n\t\t\t\t\t CORRECT ANSWER :)");
        getchar();
        scanf("%c",&inp);
      }
      else if(ia==1||ia==2||ia==3||ia==4)
      {
        wrong++;
        printf("\n\t\t\t\t\t  WRONG ANSWER :(");
        getchar();
        scanf("%c",&inp);
      }
      else
      {
        printf("\n\t\t\t\t  Invalid Option, please try again");
        getchar();
        scanf("%c",&inp);
        system("clear");
        goto test;
      }
    }
    system("clear");
    printf("\n\n\t\t\t\t   ~~~~~Topic: Technology~~~~~");
    printf("\n\n\n\t\t\t\t\tCorrect Answers:%d\n\t\t\t\t\t Wrong Answers:%d\n",corr,wrong);
    restart();
}

void topic3() //Topic name is Geograhy UI done
{
    char inp;
    int count=0,r=0,i,c,ia,corr=0,wrong=0;
    rando();
    for(i=0;i<10;i++)
    {
      system("clear");
      count++;
      test:
      printf("\n\n\t\t\t\t      ~~~~~Question %d~~~~~\n",count);
      printf("\n\t\t\t    Correct Answers=%d        Wrong Answers=%d\n\n\n\n",corr,wrong);
      r=a[i];
      switch(r)
      {
        case 1:{
                c=1;
                //c is the correct option number
                printf("\t\t   The latitudinal differences in pressure delineate a number \n\t\t    of major pressure zones, which correspond with ________\n\n\n");
                printf("\t\t\t\t     1) zones of climate\n");
                printf("\t\t\t\t     2) zones of oceans\n");
                printf("\t\t\t\t     3) zones of land\n");
                printf("\t\t\t\t     4) zones of cyclonic depressions\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("           %d",&ia);
                break;
               }
        case 2:{
                c=4;
                printf("\t\t\t The hazards of radiation belts include ________\n\n\n");
                printf("\t\t\t\t     1) deterioration of electronic circuits\n");
                printf("\t\t\t\t     2) damage of solar cells of spacecraft\n");
                printf("\t\t\t\t     3) adverse effect on living organisms\n");
                printf("\t\t\t\t     4) All of the above\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 3:{
                c=3;
                printf("\t\t   The intersecting lines drawn on maps and globes are ________\n\n\n");
                printf("\t\t\t\t     1) latitudes\n");
                printf("\t\t\t\t     2) longitudes\n");
                printf("\t\t\t\t     3) geographic grids\n");
                printf("\t\t\t\t     4) 	None of the above\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 4:{
                c=3;
                printf("\t\t\t  The great Victoria Desert is located in ________\n\n\n");
                printf("\t\t\t\t     1) Canada\n");
                printf("\t\t\t\t     2) West Africa\n");
                printf("\t\t\t\t     3) Australia\n");
                printf("\t\t\t\t     4) North America\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 5:{
                c=2;
                printf("\t\t\t The leading state in producing paper is ________\n\n\n");
                printf("\t\t\t\t     1) Bihar\n");
                printf("\t\t\t\t     2) West Bengal\n");
                printf("\t\t\t\t     3) Kerala\n");
                printf("\t\t\t\t     4) Orissa\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 6:{
                c=3;
                printf("\t\t\t   The largest dune files are found in ________\n\n\n");
                printf("\t\t\t\t     1) Middle East\n");
                printf("\t\t\t\t     2) North Africa\n");
                printf("\t\t\t\t     3) both (1) and (2)\n");
                printf("\t\t\t\t     4) None of the above\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 7:{
                c=4;
                printf("\t\t\tThe highest average salinity amongst the following\n\t\t\t\t seas is reported from ________\n\n\n");
                printf("\t\t\t\t     1) Red Sea\n");
                printf("\t\t\t\t     2) Black Sea\n");
                printf("\t\t\t\t     3) Mediterranean Sea\n");
                printf("\t\t\t\t     4) Dead Sea\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 8:{
                c=4;
                printf("\t\t The Himalayan mountain system belongs to which of the following?\n\n\n");
                printf("\t\t\t\t     1) Volcanic mountains\n");
                printf("\t\t\t\t     2) Residual mountains\n");
                printf("\t\t\t\t     3) Block mountains\n");
                printf("\t\t\t\t     4) Fold mountains\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 9:{
                c=1;
                printf("\t\t  The infrared radiation by sun are strongly absorbed by ________\n\n\n");
                printf("\t\t\t\t     1) carbon dioxide\n");
                printf("\t\t\t\t     2) water vapours\n");
                printf("\t\t\t\t     3) carbon dioxide and water vapours\n");
                printf("\t\t\t\t     4) ozone\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 10:{
                c=3;
                printf("\t\t\t   The Ice age ended about ________ years ago.\n\n\n");
                printf("\t\t\t\t     1) 140\n");
                printf("\t\t\t\t     2) 1,400\n");
                printf("\t\t\t\t     3) 14,000\n");
                printf("\t\t\t\t     4) 140,000\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        default:printf("          Invalid Input\n\n\n");
      }
      if(ia==c)
      {
        corr++;
        printf("\n\t\t\t\t\t CORRECT ANSWER :)");
        getchar();
        scanf("%c",&inp);
      }
      else if(ia==1||ia==2||ia==3||ia==4)
      {
        wrong++;
        printf("\n\t\t\t\t\t  WRONG ANSWER :(");
        getchar();
        scanf("%c",&inp);
      }
      else
      {
        printf("\n\t\t\t\t  Invalid Option, please try again");
        getchar();
        scanf("%c",&inp);
        system("clear");
        goto test;
      }
    }
    system("clear");
    printf("\n\n\t\t\t\t    ~~~~~Topic: Geography~~~~~");
    printf("\n\n\n\t\t\t\t\tCorrect Answers:%d\n\t\t\t\t\t Wrong Answers:%d\n",corr,wrong);
    restart();
}

void topic4() //Topic name is Indian History UI done
{
    char inp;
    int count=0,r=0,i,c,ia,corr=0,wrong=0;
    rando();
    for(i=0;i<10;i++)
    {
      system("clear");
      count++;
      test:
      printf("\n\n\t\t\t\t      ~~~~~Question %d~~~~~\n",count);
      printf("\n\t\t\t    Correct Answers=%d        Wrong Answers=%d\n\n\n\n",corr,wrong);
      r=a[i];
      switch(r)
      {
        case 1:{
                c=1;
                //c is the correct option number
                printf("\t\t\t  The Battle of Plassey was fought in ________\n\n\n");
                printf("\t\t\t\t     1) 1757\n");
                printf("\t\t\t\t     2) 1782\n");
                printf("\t\t\t\t     3) 1748\n");
                printf("\t\t\t\t     4) 1764\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("           %d",&ia);
                break;
               }
        case 2:{
                c=1;
                printf("\t\t Under Akbar, the Mir Bakshi was required to look after ________\n\n\n");
                printf("\t\t\t\t     1) Emilitary affairs\n");
                printf("\t\t\t\t     2) the state treasury\n");
                printf("\t\t\t\t     3) the royal household\n");
                printf("\t\t\t\t     4) the land revenue system\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 3:{
                c=3;
                printf("\t\tThe use of Kharoshti in ancient Indian architecture is the result \n\t\t\t\tof India's contact with ________\n\n\n");
                printf("\t\t\t\t     1) Central Asia\n");
                printf("\t\t\t\t     2) Iran\n");
                printf("\t\t\t\t     3) Greece\n");
                printf("\t\t\t\t     4) China\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 4:{
                c=2;
                printf("\t\t   We hear of two envoys being sent to the Roman kings, one in \n\t\t  27-28 AD to the court of Augustus and the other in 110-20 AD\n\t\t\t\t   to the court of ________\n\n\n");
                printf("\t\t\t\t     1) Cartius\n");
                printf("\t\t\t\t     2) Trajan\n");
                printf("\t\t\t\t     3) Nero\n");
                printf("\t\t\t\t     4) Brutus\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 5:{
                c=4;
                printf("\t\t   The troops raised by the emperor but not paid directly the \n\t       state and place under the charge of mansabadars were know as ________\n\n\n");
                printf("\t\t\t\t     1) Walashahi\n");
                printf("\t\t\t\t     2) Barawardi\n");
                printf("\t\t\t\t     3) JCumaki\n");
                printf("\t\t\t\t     4) Dakhili\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 6:{
                c=4;
                printf("\t\t   There was a sharp class division at Harappa and Mohen-jodaro.\n\t\t\t\tThis is clear from the ________\n\n\n");
                printf("\t\t\t\t     1) Indus seals excavated\n");
                printf("\t\t\t\t     2) religious beliefs of the Harappans\n");
                printf("\t\t\t\t     3) tools and implements used by the Harappans\n");
                printf("\t\t\t\t     4) different types of dwellings excavated\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 7:{
                c=3;
                printf("\t\t\t     Tipu sultan was the ruler of ________\n\n\n");
                printf("\t\t\t\t     1) Hyderabad\n");
                printf("\t\t\t\t     2) Madurai\n");
                printf("\t\t\t\t     3) Mysore\n");
                printf("\t\t\t\t     4) Vijayanagar\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 8:{
                c=3;
                printf("\t\t\t\tThe term 'yavanika' meant ________\n\n\n");
                printf("\t\t\t\t     1) foreign goods\n");
                printf("\t\t\t\t     2) dancer\n");
                printf("\t\t\t\t     3) curtain\n");
                printf("\t\t\t\t     4) theatre\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 9:{
                c=3;
                printf("\t\t      The title of 'Viceroy' was added to the office of the\n\t\t     Governor-General of India for the first time in ________\n\n\n");
                printf("\t\t\t\t     1) 1848 AD\n");
                printf("\t\t\t\t     2) 1856 AD\n");
                printf("\t\t\t\t     3) 1858 AD\n");
                printf("\t\t\t\t     4) 1862 AD\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        case 10:{
                c=3;
                printf("\t\tTwo of the great Mughals wrote their own memories. There were ________\n\n\n");
                printf("\t\t\t\t     1) Babar and Humayun\n");
                printf("\t\t\t\t     2) Humayun and Jahangir\n");
                printf("\t\t\t\t     3) Babar and Jahangir\n");
                printf("\t\t\t\t     4) Jahangir and Shahjahan\n");
                printf("\n\t\t\t\t   Enter correct option number: ");
                scanf("          %d",&ia);
                break;
               }
        default:printf("          Invalid Input\n\n\n");
      }
      if(ia==c)
      {
        corr++;
        printf("\n\t\t\t\t\t CORRECT ANSWER :)");
        getchar();
        scanf("%c",&inp);
      }
      else if(ia==1||ia==2||ia==3||ia==4)
      {
        wrong++;
        printf("\n\t\t\t\t\t  WRONG ANSWER :(");
        getchar();
        scanf("%c",&inp);
      }
      else
      {
        printf("\n\t\t\t\t  Invalid Option, please try again");
        getchar();
        scanf("%c",&inp);
        system("clear");
        goto test;
      }
    }
    system("clear");
    printf("\n\n\t\t\t\t ~~~~~Topic: Indian History~~~~~");
    printf("\n\n\n\t\t\t\t\tCorrect Answers:%d\n\t\t\t\t\t Wrong Answers:%d\n",corr,wrong);
    restart();
}
